### ISSUE TITLE
Setup Scraper for Twitter

### ISSUE THREAD

**Issue by dnzxy** [oth-datapipeline/scraping-scripts#2]
- [X] Get and test developer account
- [x] First Implementation
- [x] Determine which data we want to retrieve from Twitter API (Trends, Tweets, Retweets, Comments, ...)

**Comment by michaeldinzinger** [comment]
# Twitter Trends
- All trends lists are depending on a location
  - You can get the locations, for which a trends list exists, with `API.available_trends()`
  - For *Worldwide* always exists a trends list; for *Germany* probably, too; however, for e.g. *Regensburg* there's normally no Twitter trends list (only when something special happens of course)
- *Alternative:* `API.closest_trends(lat, long)` returns the locations with trends lists, closest to a specified place given with latitude and longitude
- Given a specific location, you can get the trending hashtags or names via `API.get_place_trends(location_id, ...)`
  - This is always a TOP 50 list
  - This list is not constantly changing, but remains the same for quite a while
- The trending hashtags and names can be the starting point for the search for Tweets, Retweets, Comments, ...
  - For example: Right now, this is the top trending hashtag worldwide (Idk what's it about?!):  
    `{'name': '#BinJinWedding', 'url': 'http://twitter.com/search?q=%23BinJinWedding', 'promoted_content': None, 'query': '%23BinJinWedding', 'tweet_volume': 75272}`
  - The *query* field can be used in the `client.search_all_tweets(query=..., ...)` or `client.search_recent_tweets(query=..., ...)` (*recent* search covers only the last seven days -> should be enough for our case?)
  - This hashtag has a *tweet_volume* of 75272: For sure not all of these tweets are worth scraping -> Maybe only the tweets with most likes / or the "most trending" ones (in case that's possible)?

# Tweets Search
- For a tweet, you can get all kind of additional information
  - For example: user data or geo data (in case these are available) -> Which additional information do we want to store?
- With the methods `client.search_all_tweets(query=..., ...)` and `client.search_recent_tweets(query=..., ...)` you can retrieve up to 100 tweets per call; using a *Paginator* it can be more

**Comment by dim35216** [comment]
# Twitter Trends
- All trends lists are depending on a location
  - You can get the locations, for which a trends list exists, with `API.available_trends()`
  - For *Worldwide* always exists a trends list; for *Germany* probably, too; however, for e.g. *Regensburg* there's normally no Twitter trends list (only when something special happens of course)
- *Alternative:* `API.closest_trends(lat, long)` returns the locations with trends lists, closest to a specified place given with latitude and longitude
- Given a specific location, you can get the trending hashtags or names via `API.get_place_trends(location_id, ...)`
  - This is always a TOP 50 list
  - This list is not constantly changing, but remains the same for quite a while
- The trending hashtags and names can be the starting point for the search for Tweets, Retweets, Comments, ...
  - For example: Right now, this is the top trending hashtag worldwide (Idk what's it about?!):  
    `{'name': '#BinJinWedding', 'url': 'http://twitter.com/search?q=%23BinJinWedding', 'promoted_content': None, 'query': '%23BinJinWedding', 'tweet_volume': 75272}`
  - The *query* field can be used in the `client.search_all_tweets(query=..., ...)` or `client.search_recent_tweets(query=..., ...)` (*recent* search covers only the last seven days -> should be enough for our case?)
  - This hashtag has a *tweet_volume* of 75272: For sure not all of these tweets are worth scraping -> Maybe only the tweets with most likes / or the "most trending" ones (in case that's possible)?

# Tweets Search
- For a tweet, you can get all kind of additional information
  - For example: user data or geo data (in case these are available) -> Which additional information do we want to store?
- With the methods `client.search_all_tweets(query=..., ...)` and `client.search_recent_tweets(query=..., ...)` you can retrieve up to 100 tweets per call; using a *Paginator* it can be more

**Comment by dnzxy** [comment]
Hi, to add to your points, @dim35216 : Going by this [overview](https://developer.twitter.com/en/products/twitter-api/academic-research#:~:text=New%20and%20existing%20Twitter%20developers,an%20academic%20institution%20or%20university.) of the benefits provided through the Academic Research access, we could get up up to 480,000* tweets every day 

50 requests / 15 min x 4 x 100 x 24 = 480,000.

If we choose to scrape different sources from Twitter, i.e. get an amount x of tweets via search and then another batch y by fetching trends like 4-6x daily, we would still get a huge amount of tweets, even with these limits. I'm certain that the amount of streams would be sufficient for our purposes. What do you guys think?
