### ISSUE TITLE
Setup of Scraper for Reddit

### ISSUE THREAD

**Issue by dnzxy** [oth-datapipeline/scraping-scripts#3]
- Basic scraper for reddit posts only
- Handling of link-only-posts, comments, etc. in a later step

- [x] Create Reddit application for getting the authentication secret for the API
- [x] First Implementation
- [x] Determine which data we want to retrieve from theAPI (Posts, Comments, ...):

**Comment by dim35216** [comment]
__client_id = 'rqjVhdrDgzHWuf771sYjgg'__
__client_secret = 'F4ygITGp5hC9CjvfEqfLOyK0htgWyw'__

Example code:
```import praw

client_id = 'rqjVhdrDgzHWuf771sYjgg'
client_secret = 'F4ygITGp5hC9CjvfEqfLOyK0htgWyw'

reddit = praw.Reddit(
    client_id = client_id,
    client_secret = client_secret,
    username = '...',
    password = '...',
    user_agent = 'My first user agent'
)```

**Comment by lukasgraef** [comment]
__client_id = 'censored'__
__client_secret = 'censored__

Example code:
```import praw

client_id = 'censored'
client_secret = 'censored'

reddit = praw.Reddit(
    client_id = client_id,
    client_secret = client_secret,
    username = '...',
    password = '...',
    user_agent = 'My first user agent'
)```
